2023-10-29 11:40:35,449 INFO    MainThread:13252 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-29 11:40:35,449 INFO    MainThread:13252 [wandb_setup.py:_flush():76] Configure stats pid to 13252
2023-10-29 11:40:35,449 INFO    MainThread:13252 [wandb_setup.py:_flush():76] Loading settings from C:\Users\glebk\.config\wandb\settings
2023-10-29 11:40:35,449 INFO    MainThread:13252 [wandb_setup.py:_flush():76] Loading settings from D:\Study\BP\Implementation\ml_tuning\ml_tuning\wandb\settings
2023-10-29 11:40:35,449 INFO    MainThread:13252 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-29 11:40:35,449 INFO    MainThread:13252 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-29 11:40:35,450 INFO    MainThread:13252 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'ml_tuning\\heartdesease_privacy.py', 'program_abspath': 'D:\\Study\\BP\\Implementation\\ml_tuning\\ml_tuning\\heartdesease_privacy.py', 'program': 'D:\\Study\\BP\\Implementation\\ml_tuning\\ml_tuning\\heartdesease_privacy.py'}
2023-10-29 11:40:35,450 INFO    MainThread:13252 [wandb_init.py:_log_setup():528] Logging user logs to D:\Study\BP\Implementation\ml_tuning\ml_tuning\wandb\run-20231029_114035-62jvmhln\logs\debug.log
2023-10-29 11:40:35,450 INFO    MainThread:13252 [wandb_init.py:_log_setup():529] Logging internal logs to D:\Study\BP\Implementation\ml_tuning\ml_tuning\wandb\run-20231029_114035-62jvmhln\logs\debug-internal.log
2023-10-29 11:40:35,450 INFO    MainThread:13252 [wandb_init.py:init():568] calling init triggers
2023-10-29 11:40:35,450 INFO    MainThread:13252 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.015, 'architecture': 'CNN', 'dataset': 'heart_2020_cleared', 'epochs': 60}
2023-10-29 11:40:35,451 INFO    MainThread:13252 [wandb_init.py:init():613] wandb.init() called when a run is still active
2023-10-29 11:44:44,810 WARNING MsgRouterThr:13252 [router.py:message_loop():77] message_loop has been closed
